! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : box_Monitor.f90
! Time                 : Thu Oct 21 15:31:35 2021
! Working directory    : /mnt/d/OneDrive/modelling/kpp/box_mercury_updated
! Equation file        : box.kpp
! Output root filename : box
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE box_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'I2_flux        ','I2O5           ','CH3I           ', &
     'C2H5I          ','CH2I2          ','CH2IBr         ', &
     'CH2ICl         ','nC3H7I         ','iC3H7I         ', &
     'IBr            ','O1D            ','HOCl           ', &
     'OClO           ','Hg_DryDep      ','Hg_WetDep      ', &
     'Hg_AerDep      ','CO2            ','H              ', &
     'NA             ','SA             ','SO3            ', &
     'CH3CO          ','DUMMY          ','DMSO           ', &
     'HgBr_aq        ','HgBr2_aq       ','HgBrOH_aq      ', &
     'HgBrCl_aq      ','HgBrNO2_aq     ','HgBrHO2_aq     ', &
     'HgBrO_aq       ','HgOH_aq        ','HgOHOH_aq      ', &
     'HgOHCl_aq      ','HgOHNO2_aq     ','HgOHNO2        ', &
     'HgOHHO2_aq     ','HgOHO_aq       ','HgCl_aq        ', &
     'HgCl2_aq       ','HgClNO2_aq     ','HgClHO2_aq     ', &
     'HgClO_aq       ','N2O5           ','CH3O2NO2       ', &
     'HgO            ','HSO3           ','CH3CHO         ', &
     'I2O4           ','HgOHO          ','HgClNO2        ', &
     'HgBrNO2        ','BrCl           ','HgOHHO2        ', &
     'ICl            ','ClO            ','HgCl2          ', &
     'HgOHOH         ','H2             ','H2O2           ', &
     'BrNO2          ','HONO           ','HO2NO2         ', &
     'HgBr2          ','I2O2           ','I2O3           ', &
     'BrNO           ','INO2           ','HgBrO          ', &
     'HgClO          ','SO2            ','INO            ', &
     'CH3OH          ','HNO3           ','DMS            ', &
     'HgClHO2        ','HgBrHO2        ','CH3NO3         ', &
     'CH3O           ','HgBrCl         ','CH3OOH         ', &
     'HBr            ','BrONO2         ','HI             ', &
     'IONO2          ','HgOHCl         ','HOI            ', &
     'HgBrOH         ','Br2            ','OIO            ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(22) :: SPC_NAMES_1 = (/ &
     'HCHO           ','HOBr           ','Cl             ', &
     'HgOH           ','HgCl           ','HgBr           ', &
     'CH3O2          ','I2             ','I              ', &
     'OH             ','NO             ','NO3            ', &
     'IO             ','Br             ','HO2            ', &
     'O              ','BrO            ','Hg             ', &
     'O3             ','NO2            ','CO             ', &
     'CH4            ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(112) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, PARAMETER, DIMENSION(49) :: LOOKAT = (/ &
      14, 15, 16, 25, 26, 27, 28, 29, 30, 31, 32, 33, &
      34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 50, 51, &
      52, 54, 57, 58, 64, 69, 70, 76, 77, 80, 86, 88, &
      89, 93, 94, 95, 96,100,101,104,105,107,108,109, &
     110 /)

  INTEGER, PARAMETER, DIMENSION(5) :: MONITOR = (/ &
     100,101,105,107,109 /)

  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '      I2_flux --> 25 HOI + I2                                                                       ', &
     '           I2 --> 2 I                                                                               ', &
     '           IO --> I + O                                                                             ', &
     '          OIO --> I                                                                                 ', &
     '         I2O2 --> 2 IO                                                                              ', &
     '         I2O3 --> OIO + IO                                                                          ', &
     '         I2O4 --> 2 OIO                                                                             ', &
     '         I2O5 --> OIO + IO                                                                          ', &
     '          HOI --> I + OH                                                                            ', &
     '           HI --> H + I                                                                             ', &
     '          INO --> I + NO                                                                            ', &
     '         INO2 --> 0.5 I + 0.5 NO + 0.5 IO + 0.5 NO2                                                 ', &
     '        IONO2 --> I + NO3                                                                           ', &
     '          IBr --> I + Br                                                                            ', &
     '          ICl --> Cl + I                                                                            ', &
     '         CH3I --> I                                                                                 ', &
     '        CH2I2 --> 2 I                                                                               ', &
     '       CH2ICl --> Cl + I                                                                            ', &
     '       CH2IBr --> I + Br                                                                            ', &
     '        C2H5I --> I                                                                                 ', &
     '       nC3H7I --> I                                                                                 ', &
     '       iC3H7I --> I                                                                                 ', &
     '      I2 + O3 --> OIO + IO                                                                          ', &
     '       I + O3 --> IO                                                                                ', &
     '      IO + O3 --> OIO                                                                               ', &
     '       I2 + O --> I + IO                                                                            ', &
     '       IO + O --> I                                                                                 ', &
     '      NO + IO --> I + NO2                                                                           ', &
     '     OIO + NO --> IO + NO2                                                                          ', &
     '     I2 + NO3 --> IONO2 + I                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '      I + NO3 --> IO + NO2                                                                          ', &
     '     NO3 + IO --> OIO + NO2                                                                         ', &
     '     HI + NO3 --> HNO3 + I                                                                          ', &
     '      I2 + OH --> HOI + I                                                                           ', &
     '      OH + IO --> I + HO2                                                                           ', &
     '      HI + OH --> I                                                                                 ', &
     '     HOI + OH --> IO                                                                                ', &
     '      I + HO2 --> HI                                                                                ', &
     '     IO + HO2 --> HOI                                                                               ', &
     '         2 IO --> OIO + I                                                                           ', &
     '         2 IO --> I2O2                                                                              ', &
     '     OIO + IO --> I2O3                                                                              ', &
     '        2 OIO --> I2O4                                                                              ', &
     '    I2O2 + O3 --> I2O3                                                                              ', &
     '    I2O3 + O3 --> I2O4                                                                              ', &
     '     DMS + IO --> DMSO + I                                                                          ', &
     '        2 INO --> I2 + 2 NO                                                                         ', &
     '       2 INO2 --> I2 + 2 NO2                                                                        ', &
     '    IONO2 + I --> I2 + NO3                                                                          ', &
     '         I2O2 --> OIO + I                                                                           ', &
     '         I2O2 --> 2 IO                                                                              ', &
     '         I2O4 --> 2 OIO                                                                             ', &
     '        IONO2 --> IO + NO2                                                                          ', &
     '         INO2 --> I + NO2                                                                           ', &
     '       I + NO --> INO                                                                               ', &
     '     IO + NO2 --> IONO2                                                                             ', &
     '      I + NO2 --> INO2                                                                              ', &
     '     OIO + OH --> HOI                                                                               ', &
     '          HOI --> 0.5 I2                                                                            ', &
     '           HI --> 0.5 I2                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '         INO2 --> 0.5 I2                                                                            ', &
     '        IONO2 --> 0.5 I2                                                                            ', &
     '           IO --> 0.5 I2                                                                            ', &
     '          Br2 --> 2 Br                                                                              ', &
     '         BrCl --> Cl + Br                                                                           ', &
     '          BrO --> Br + O3                                                                           ', &
     '       BrONO2 --> 0.3 NO3 + 0.3 Br + 0.7 BrO + 0.7 NO2                                              ', &
     '        BrNO2 --> 0.5 NO + 0.5 Br + 0.5 BrO + 0.5 NO2                                               ', &
     '         HOBr --> OH + Br                                                                           ', &
     '      Br + O3 --> BrO                                                                               ', &
     '     HBr + OH --> Br                                                                                ', &
     '     Br + HO2 --> HBr                                                                               ', &
     '    HCHO + Br --> HBr + HO2 + CO                                                                    ', &
     '  CH3CHO + Br --> CH3CO + HBr                                                                       ', &
     '    HO2 + BrO --> HOBr                                                                              ', &
     '     NO + BrO --> Br + NO2                                                                          ', &
     '    DMS + BrO --> DMSO + Br                                                                         ', &
     '        2 BrO --> 2 Br                                                                              ', &
     '        2 BrO --> Br2                                                                               ', &
     '       BrONO2 --> BrO + NO2                                                                         ', &
     '     Br2 + OH --> HOBr + Br                                                                         ', &
     '  BrONO2 + Br --> Br2 + NO3                                                                         ', &
     '  BrONO2 + NO --> BrNO + NO3                                                                        ', &
     'BrNO + BrONO2 --> Br2 + 2 NO2                                                                       ', &
     '     HOBr + O --> OH + BrO                                                                          ', &
     '    BrCl + OH --> HOCl + Br                                                                         ', &
     '     Br + NO2 --> BrNO2                                                                             ', &
     '    BrO + NO2 --> BrONO2                                                                            ', &
     '         HOBr --> 0.5 Br2                                                                           ', &
     '          HBr --> 0.5 Br2                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '        BrNO2 --> 0.5 Br2                                                                           ', &
     '       BrONO2 --> 0.5 Br2                                                                           ', &
     '     ClO + IO --> OClO + I                                                                          ', &
     '     ClO + IO --> Cl + I                                                                            ', &
     '     ClO + IO --> ICl                                                                               ', &
     '      IO + Br --> I + BrO                                                                           ', &
     '     IO + BrO --> I + Br                                                                            ', &
     '     IO + BrO --> OIO + Br                                                                          ', &
     '      Br + Hg --> HgBr                                                                              ', &
     '         HgBr --> Br + Hg                                                                           ', &
     '    HgBr + Br --> Br2 + Hg                                                                          ', &
     '    HgBr + Br --> HgBr2                                                                             ', &
     '    HgBr + OH --> HgBrOH                                                                            ', &
     '    Cl + HgBr --> HgBrCl                                                                            ', &
     '   HgBr + NO2 --> HgBrNO2                                                                           ', &
     '   HgBr + HO2 --> HgBrHO2                                                                           ', &
     '    HgBr + O3 --> HgBrO                                                                             ', &
     '  HgBrO + CH4 --> HgBrOH + CH3O2                                                                    ', &
     '   HgBrO + CO --> CO2 + HgBr                                                                        ', &
     '      OH + Hg --> HgOH                                                                              ', &
     '         HgOH --> OH + Hg                                                                           ', &
     '    HgOH + Br --> HgBrOH                                                                            ', &
     '    HgOH + OH --> HgOHOH                                                                            ', &
     '    Cl + HgOH --> HgOHCl                                                                            ', &
     '   HgOH + NO2 --> HgOHNO2                                                                           ', &
     '   HgOH + HO2 --> HgOHHO2                                                                           ', &
     '    HgOH + O3 --> HgOHO                                                                             ', &
     '  HgOHO + CH4 --> HgOHOH + CH3O2                                                                    ', &
     '   HgOHO + CO --> CO2 + HgOH                                                                        ', &
     '      Cl + Hg --> HgCl                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '    Cl + HgCl --> HgCl2                                                                             ', &
     '    HgCl + Br --> HgBrCl                                                                            ', &
     '    HgCl + OH --> HgOHCl                                                                            ', &
     '   HgCl + NO2 --> HgClNO2                                                                           ', &
     '   HgCl + HO2 --> HgClHO2                                                                           ', &
     '    HgCl + O3 --> HgClO                                                                             ', &
     '  HgClO + CH4 --> HgOHCl + CH3O2                                                                    ', &
     '   HgClO + CO --> CO2 + HgCl                                                                        ', &
     '         HgBr --> Br + Hg                                                                           ', &
     '        HgBrO --> HgO + Br                                                                          ', &
     '        HgBr2 --> 0.6 HgBr + 1.4 Br + 0.4 Hg                                                        ', &
     '       HgBrOH --> 0.35 HgOH + 0.15 HgBr + 0.65 OH + 0.85 Br + 0.5 Hg                                ', &
     '       HgBrCl --> Cl + 0.6 HgBr + 0.4 Br + 0.4 Hg                                                   ', &
     '      HgBrNO2 --> 0.9 HgBrO + 0.1 HgBr + 0.9 NO + 0.1 NO2                                           ', &
     '      HgBrHO2 --> 0.31 HgBrOH + 0.03 HgBr + 0.66 Br + 0.69 HO2 + 0.66 Hg ... etc.                   ', &
     '          HgO --> O + Hg                                                                            ', &
     '         HgOH --> OH + Hg                                                                           ', &
     '       HgOHOH --> 0.5 HgOH + 1.5 OH + 0.5 Hg                                                        ', &
     '       HgOHCl --> 0.85 Cl + 0.35 HgOH + 0.15 HgCl + 0.65 OH + 0.5 Hg                                ', &
     '      HgOHNO2 --> HgOH + NO2                                                                        ', &
     '      HgOHHO2 --> HgOH + HO2                                                                        ', &
     '         HgCl --> Cl + Hg                                                                           ', &
     '        HgClO --> HgO + Cl                                                                          ', &
     '        HgCl2 --> 1.4 Cl + 0.6 HgCl + 0.4 Hg                                                        ', &
     '      HgClNO2 --> 0.9 HgClO + 0.1 HgCl + 0.9 NO + 0.1 NO2                                           ', &
     '      HgClHO2 --> 0.31 HgOHCl + 0.66 Cl + 0.03 HgCl + 0.69 HO2 + 0.66 Hg ... etc.                   ', &
     '         HgBr --> HgBr_aq                                                                           ', &
     '        HgBr2 --> HgBr2_aq                                                                          ', &
     '       HgBrOH --> HgBrOH_aq                                                                         ', &
     '       HgBrCl --> HgBrCl_aq                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '      HgBrNO2 --> HgBrNO2_aq                                                                        ', &
     '      HgBrHO2 --> HgBrHO2_aq                                                                        ', &
     '        HgBrO --> HgBrO_aq                                                                          ', &
     '         HgOH --> HgOH_aq                                                                           ', &
     '       HgOHOH --> HgOHOH_aq                                                                         ', &
     '       HgOHCl --> HgOHCl_aq                                                                         ', &
     '      HgOHNO2 --> HgOHNO2_aq                                                                        ', &
     '      HgOHHO2 --> HgOHHO2_aq                                                                        ', &
     '        HgOHO --> HgOHO_aq                                                                          ', &
     '         HgCl --> HgCl_aq                                                                           ', &
     '        HgCl2 --> HgCl2_aq                                                                          ', &
     '      HgClNO2 --> HgClNO2_aq                                                                        ', &
     '      HgClHO2 --> HgClHO2_aq                                                                        ', &
     '        HgClO --> HgClO_aq                                                                          ', &
     '      HgBr_aq --> HgBr                                                                              ', &
     '     HgBr2_aq --> HgBr2                                                                             ', &
     '    HgBrOH_aq --> HgBrOH                                                                            ', &
     '    HgBrCl_aq --> HgBrCl                                                                            ', &
     '   HgBrNO2_aq --> HgBrNO2                                                                           ', &
     '   HgBrHO2_aq --> HgBrHO2                                                                           ', &
     '     HgBrO_aq --> HgBrO                                                                             ', &
     '      HgOH_aq --> HgOH                                                                              ', &
     '    HgOHOH_aq --> HgOHOH                                                                            ', &
     '    HgOHCl_aq --> HgOHCl                                                                            ', &
     '   HgOHNO2_aq --> HgOHNO2                                                                           ', &
     '   HgOHHO2_aq --> HgOHHO2                                                                           ', &
     '     HgOHO_aq --> HgOHO                                                                             ', &
     '      HgCl_aq --> HgCl                                                                              ', &
     '     HgCl2_aq --> HgCl2                                                                             ', &
     '   HgClNO2_aq --> HgClNO2                                                                           ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '   HgClHO2_aq --> HgClHO2                                                                           ', &
     '     HgClO_aq --> HgClO                                                                             ', &
     '         HgBr --> Hg_DryDep                                                                         ', &
     '        HgBr2 --> Hg_DryDep                                                                         ', &
     '       HgBrOH --> Hg_DryDep                                                                         ', &
     '       HgBrCl --> Hg_DryDep                                                                         ', &
     '      HgBrNO2 --> Hg_DryDep                                                                         ', &
     '      HgBrHO2 --> Hg_DryDep                                                                         ', &
     '        HgBrO --> Hg_DryDep                                                                         ', &
     '         HgOH --> Hg_DryDep                                                                         ', &
     '       HgOHOH --> Hg_DryDep                                                                         ', &
     '       HgOHCl --> Hg_DryDep                                                                         ', &
     '      HgOHNO2 --> Hg_DryDep                                                                         ', &
     '      HgOHHO2 --> Hg_DryDep                                                                         ', &
     '        HgOHO --> Hg_DryDep                                                                         ', &
     '         HgCl --> Hg_DryDep                                                                         ', &
     '        HgCl2 --> Hg_DryDep                                                                         ', &
     '      HgClNO2 --> Hg_DryDep                                                                         ', &
     '      HgClHO2 --> Hg_DryDep                                                                         ', &
     '        HgClO --> Hg_DryDep                                                                         ', &
     '         HgBr --> Hg_WetDep                                                                         ', &
     '        HgBr2 --> Hg_WetDep                                                                         ', &
     '       HgBrOH --> Hg_WetDep                                                                         ', &
     '       HgBrCl --> Hg_WetDep                                                                         ', &
     '      HgBrNO2 --> Hg_WetDep                                                                         ', &
     '      HgBrHO2 --> Hg_WetDep                                                                         ', &
     '        HgBrO --> Hg_WetDep                                                                         ', &
     '         HgOH --> Hg_WetDep                                                                         ', &
     '       HgOHOH --> Hg_WetDep                                                                         ', &
     '       HgOHCl --> Hg_WetDep                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '      HgOHNO2 --> Hg_WetDep                                                                         ', &
     '      HgOHHO2 --> Hg_WetDep                                                                         ', &
     '        HgOHO --> Hg_WetDep                                                                         ', &
     '         HgCl --> Hg_WetDep                                                                         ', &
     '        HgCl2 --> Hg_WetDep                                                                         ', &
     '      HgClNO2 --> Hg_WetDep                                                                         ', &
     '      HgClHO2 --> Hg_WetDep                                                                         ', &
     '        HgClO --> Hg_WetDep                                                                         ', &
     '      HgBr_aq --> Hg_AerDep                                                                         ', &
     '     HgBr2_aq --> Hg_AerDep                                                                         ', &
     '    HgBrOH_aq --> Hg_AerDep                                                                         ', &
     '    HgBrCl_aq --> Hg_AerDep                                                                         ', &
     '   HgBrNO2_aq --> Hg_AerDep                                                                         ', &
     '   HgBrHO2_aq --> Hg_AerDep                                                                         ', &
     '     HgBrO_aq --> Hg_AerDep                                                                         ', &
     '      HgOH_aq --> Hg_AerDep                                                                         ', &
     '    HgOHOH_aq --> Hg_AerDep                                                                         ', &
     '    HgOHCl_aq --> Hg_AerDep                                                                         ', &
     '   HgOHNO2_aq --> Hg_AerDep                                                                         ', &
     '   HgOHHO2_aq --> Hg_AerDep                                                                         ', &
     '     HgOHO_aq --> Hg_AerDep                                                                         ', &
     '      HgCl_aq --> Hg_AerDep                                                                         ', &
     '     HgCl2_aq --> Hg_AerDep                                                                         ', &
     '   HgClNO2_aq --> Hg_AerDep                                                                         ', &
     '   HgClHO2_aq --> Hg_AerDep                                                                         ', &
     '     HgClO_aq --> Hg_AerDep                                                                         ', &
     '            O --> O3                                                                                ', &
     '       O + O3 --> DUMMY                                                                             ', &
     '       NO + O --> NO2                                                                               ', &
     '      O + NO2 --> NO                                                                                ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '      O + NO2 --> NO3                                                                               ', &
     '          O1D --> O                                                                                 ', &
     '      NO + O3 --> NO2                                                                               ', &
     '     O3 + NO2 --> NO3                                                                               ', &
     '         2 NO --> 2 NO2                                                                             ', &
     '     NO + NO3 --> 2 NO2                                                                             ', &
     '    NO3 + NO2 --> NO + NO2                                                                          ', &
     '    NO3 + NO2 --> N2O5                                                                              ', &
     '          O1D --> 2 OH                                                                              ', &
     '      OH + O3 --> HO2                                                                               ', &
     '      H2 + OH --> HO2                                                                               ', &
     '      OH + CO --> HO2                                                                               ', &
     '    H2O2 + OH --> HO2                                                                               ', &
     '     HO2 + O3 --> OH                                                                                ', &
     '     OH + HO2 --> DUMMY                                                                             ', &
     '        2 HO2 --> H2O2                                                                              ', &
     '      OH + NO --> HONO                                                                              ', &
     '     OH + NO2 --> HNO3                                                                              ', &
     '     OH + NO3 --> HO2 + NO2                                                                         ', &
     '     NO + HO2 --> OH + NO2                                                                          ', &
     '    HO2 + NO2 --> HO2NO2                                                                            ', &
     '  HO2NO2 + OH --> NO2                                                                               ', &
     '    NO3 + HO2 --> OH + NO2                                                                          ', &
     '    HONO + OH --> NO2                                                                               ', &
     '    HNO3 + OH --> NO3                                                                               ', &
     '      SO2 + O --> SO3                                                                               ', &
     '     SO2 + OH --> HSO3                                                                              ', &
     '         HSO3 --> SO3 + HO2                                                                         ', &
     '         HNO3 --> NA                                                                                ', &
     '         N2O5 --> 2 NA                                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '          SO3 --> SA                                                                                ', &
     '           O3 --> O1D                                                                               ', &
     '           O3 --> O                                                                                 ', &
     '         H2O2 --> 2 OH                                                                              ', &
     '          NO2 --> NO + O                                                                            ', &
     '          NO3 --> NO                                                                                ', &
     '          NO3 --> O + NO2                                                                           ', &
     '         HONO --> OH + NO                                                                           ', &
     '         HNO3 --> OH + NO2                                                                          ', &
     '         N2O5 --> NO3 + NO2                                                                         ', &
     '       HO2NO2 --> HO2 + NO2                                                                         ', &
     '           OH --> DUMMY                                                                             ', &
     '          HO2 --> DUMMY                                                                             ', &
     '        CH3O2 --> DUMMY                                                                             ', &
     '         HNO3 --> DUMMY                                                                             ', &
     '         N2O5 --> DUMMY                                                                             ', &
     '          NO3 --> DUMMY                                                                             ', &
     '          NO2 --> DUMMY                                                                             ', &
     '         H2O2 --> DUMMY                                                                             ', &
     '        CH3OH --> DUMMY                                                                             ', &
     '       CH3OOH --> DUMMY                                                                             ', &
     '         HCHO --> DUMMY                                                                             ', &
     '       CH3CHO --> DUMMY                                                                             ', &
     '     Cl + CH4 --> CH3O2                                                                             ', &
     '     OH + CH4 --> CH3O2                                                                             ', &
     '  CH3O2 + HO2 --> CH3OOH                                                                            ', &
     '  CH3O2 + HO2 --> HCHO                                                                              ', &
     '   CH3O2 + NO --> CH3NO3                                                                            ', &
     '   CH3O2 + NO --> CH3O + NO2                                                                        ', &
     '  CH3O2 + NO2 --> CH3O2NO2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(16) :: EQN_NAMES_10 = (/ &
     '  CH3O2 + NO3 --> CH3O + NO2                                                                        ', &
     '        CH3O2 --> CH3O                                                                              ', &
     '        CH3O2 --> CH3OH                                                                             ', &
     '        CH3O2 --> HCHO                                                                              ', &
     '       CH3OOH --> CH3O + OH                                                                         ', &
     '  CH3OOH + OH --> CH3O2                                                                             ', &
     '  CH3OOH + OH --> HCHO + OH                                                                         ', &
     '         HCHO --> 2 HO2 + CO                                                                        ', &
     '         HCHO --> H2 + CO                                                                           ', &
     '   HCHO + NO3 --> HNO3 + HO2 + CO                                                                   ', &
     '    HCHO + OH --> HO2 + CO                                                                          ', &
     '       CH3NO3 --> CH3O + NO2                                                                        ', &
     '  CH3NO3 + OH --> HCHO + NO2                                                                        ', &
     '         CH3O --> HCHO + HO2                                                                        ', &
     '     CH3O2NO2 --> CH3O2 + NO2                                                                       ', &
     '   CH3OH + OH --> HCHO + HO2                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(316) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10 /)

! INLINED global variables

! End INLINED global variables


END MODULE box_Monitor
