! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : box_Initialize.f90
! Time                 : Thu Oct 21 15:31:35 2021
! Working directory    : /mnt/d/OneDrive/modelling/kpp/box_mercury_updated
! Equation file        : box.kpp
! Output root filename : box
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE box_Initialize

  USE box_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE box_Global

  INTEGER :: i
  REAL(kind=dp) :: x

  CFACTOR = 2.460000e+07_dp

  x = (0.)*CFACTOR
  DO i = 1, NVAR
    VAR(i) = x
  END DO

  x = (0.)*CFACTOR
  DO i = 1, NFIX
    FIX(i) = x
  END DO

  FIX(1) = (0.0268)*CFACTOR
  FIX(2) = (10.E3)*CFACTOR
  FIX(3) = (5.0)*CFACTOR
  FIX(4) = (50.E3)*CFACTOR
  FIX(5) = (750.E3)*CFACTOR
! constant rate coefficients
  RCONST(25) = 3.6e-16
  RCONST(26) = 1.25e-10
  RCONST(27) = 1.4e-10
  RCONST(30) = 1.5e-12
  RCONST(31) = 1e-10
  RCONST(32) = 9e-12
  RCONST(34) = 1.8e-10
  RCONST(35) = 1e-10
  RCONST(37) = 2e-13
  RCONST(44) = 6e-13
  RCONST(45) = 6e-13
  RCONST(71) = 1.1e-11
  RCONST(82) = 4.9e-11
  RCONST(83) = 3e-19
  RCONST(84) = 1e-16
  RCONST(86) = 1.5e-12
  RCONST(96) = 2.49e-11
  RCONST(101) = 3.9e-11
  RCONST(104) = 3e-11
  RCONST(107) = 1e-10
  RCONST(108) = 2.63e-13
  RCONST(112) = 3e-11
  RCONST(113) = 3e-11
  RCONST(114) = 3e-11
  RCONST(117) = 3e-11
  RCONST(121) = 3e-11
  RCONST(122) = 3e-11
  RCONST(123) = 3e-11
  RCONST(126) = 3e-11
  RCONST(201) = 1.15e-05
  RCONST(202) = 1.15e-05
  RCONST(203) = 1.15e-05
  RCONST(204) = 1.15e-05
  RCONST(205) = 1.15e-05
  RCONST(206) = 1.15e-05
  RCONST(207) = 1.15e-05
  RCONST(208) = 1.15e-05
  RCONST(209) = 1.15e-05
  RCONST(210) = 1.15e-05
  RCONST(211) = 1.15e-05
  RCONST(212) = 1.15e-05
  RCONST(213) = 1.15e-05
  RCONST(214) = 1.15e-05
  RCONST(215) = 1.15e-05
  RCONST(216) = 1.15e-05
  RCONST(217) = 1.15e-05
  RCONST(218) = 1.15e-05
! END constant rate coefficients

! INLINED initializations

        TSTART = (0*3600)
        TEND = TSTART + (10*24*3600)
        DT = 1*60
        TEMP = 242. ! Kelvin
        ASA = 3.E-8 !(cm-2 cm-3)
        !ASA = 1.E-7 !(cm-2 cm-3)
        AVOL = 1.E-11 !(cm-3 cm-3)
        PRESSURE = 2.46E19 !(molec. cm-3)
        RelHum = 85.
        H_alt = 1000.*100.
        windspeed = 3. ! m s-1
        aerosol_loss = 1./(3.*24*3600.) !Lost over three days

! End INLINED initializations

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE box_Initialize

