! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : box_Rates.f90
! Time                 : Thu Oct 21 15:31:35 2021
! Working directory    : /mnt/d/OneDrive/modelling/kpp/box_mercury_updated
! Equation file        : box.kpp
! Output root filename : box
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE box_Rates

  USE box_Parameters
  USE box_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE box_Parameters
      !USE box_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST

 
    ! generic reaction rate variables
    REAL(dp) :: kro2no, kro2ho2, kapho2, kapno, kro2no3, kno3al, kdec
    REAL(dp) :: krosec, kalkoxy, kalkpxy, kroprim, KCH3O2, K298CH3O2
    ! variables for calculation of kfpan and kbpan
    REAL(dp) :: kfpan, kbpan, kc0, kci, krc, fcc, fc, kd0, kdi, krd, fcd, fd
    ! variables for calculation of organic complex reactions rates
    REAL(dp) :: k0, ki, kr, nc, M, o2, n2, Pair, H2O, h_fact
    REAL(dp) :: kmt01, kmt02, kmt03, kmt04, kmt05, kmt06, kmt07, kmt08
    REAL(dp) :: kmt09, kmt10, kmt11, kmt12, kmt13, kmt14, kmt15, kmt16
    REAL(dp) :: kmt17, kmt18, k1, k2, k3, k4
    REAL(dp) :: RK0, RKI, Fcr, ETI, kino, kino2, kiono2, koiooh,koioio
    REAL(dp) :: koiooio, kti2o4, ktiono2, kbrno2, kbrono2, RO2
    REAL(dp) :: u_INO2, u_IONO2, u_HI, u_HOI, u_IO, u_BrNO2, u_BrONO2
    REAL(dp) :: u_HBr, u_HOBr, u_OH, u_HO2, u_CH3O2, u_HNO3, u_N2O5
    REAL(dp) :: u_NO3, u_NO2, u_HgBr, u_HgBr2, u_HgBrOH, u_HgBrCl,u_HgBrNO2 
    REAL(dp) :: u_HgBrHO2,u_HgBrO,u_HgOH,u_HgOHOH,u_HgOHCl,u_HgOHNO2,u_HgOHHO2
    REAL(dp) :: u_HgOHO,u_HgCl,u_HgCl2,u_HgClNO2,u_HgClHO2,u_HgClO 
    REAL(dp) :: v_HO2, v_H2O2, v_CH3OH, v_CH3OOH, v_C2H5OOH, v_IC3H7OOH
    REAL(dp) :: v_NC3H7OOH, v_HCHO, v_CH3CHO, v_C2H5CHO, v_C3H7CHO
    REAL(dp) :: v_HNO3,v_GLYOX, v_Hg, hggamma
    REAL(dp) :: khgbrno2,khgbrho2,khgclno2,khgclho2

    !Constants being used for calculating rate constants
    M = Cair
    o2 = M * 0.2095
    n2 = M * 0.79
    Pair = M *1013.25 / 2.46E19
    h_fact = (AVOG*avol)/(1000.*Cair);
    !arden-buck
    H2O = (RelHum/100.)*(1./1.381E-19/(Temp))*(1.0007+Pair*3.46E-6)* &
          6.1121*exp(17.2694*(Temp-273.15)/(Temp-273.15+238.3))
    !H2O = 0.146*1E-2*PRESSURE
    
    hggamma = 0.1
    
    !! Uptake coefficients
    !Iodine
    u_INO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.173))**0.5)*0.1*ASA*100.
    u_IONO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.189))**0.5)*0.1*ASA*100.
    u_HI = 0.25*(((8.*8.3145*TEMP)/(3.14*0.128))**0.5)*0.1*ASA*100.
    u_HOI = 0.25*(((8.*8.3145*TEMP)/(3.14*0.144))**0.5)*0.031*ASA*100.
    u_IO = 0.25*(((8.*8.3145*TEMP)/(3.14*0.143))**0.5)*0.5*ASA*100.
    !Bromine
    u_BrNO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.126))**0.5)*0.1*ASA*100.
    u_BrONO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.142))**0.5)*0.1*ASA*100.
    u_HBr = 0.25*(((8.*8.3145*TEMP)/(3.14*0.81))**0.5)*0.1*ASA*100.
    u_HOBr = 0.25*(((8.*8.3145*TEMP)/(3.14*0.097))**0.5)*0.031*ASA*100.
    !Inorganic
    u_OH = 0.25*(((8.*8.3145*TEMP)/(3.14*0.017))**0.5)*0.000012* &
            EXP(1750/TEMP)*ASA*100.
    u_HO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.033))**0.5)*0.4*ASA*100.
    u_CH3O2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.047))**0.5)*0.004*ASA*100.
    u_HNO3 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.063))**0.5)*0.014*ASA*100.
    u_N2O5 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.108))**0.5)*0.03*ASA*100.
    u_NO3 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.062))**0.5)*0.003*ASA*100.
    u_NO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.03))**0.5)*0.0004*ASA*100.
    
    !Mercury
    !Br
    u_HgBr = 0.25*(((8.*8.3145*TEMP)/(3.14*0.280))**0.5)*hggamma*ASA*100.
    u_HgBr2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.360))**0.5)*hggamma*ASA*100.
    u_HgBrOH = 0.25*(((8.*8.3145*TEMP)/(3.14*0.297))**0.5)*hggamma*ASA*100.
    u_HgBrCl = 0.25*(((8.*8.3145*TEMP)/(3.14*0.315))**0.5)*hggamma*ASA*100.
    u_HgBrNO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.326))**0.5)*hggamma*ASA*100.
    u_HgBrHO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.303))**0.5)*hggamma*ASA*100.
	u_HgBrO = 0.25*(((8.*8.3145*TEMP)/(3.14*0.296))**0.5)*hggamma*ASA*100.
	!OH
    u_HgOH = 0.25*(((8.*8.3145*TEMP)/(3.14*0.217))**0.5)*hggamma*ASA*100.
    u_HgOHOH = 0.25*(((8.*8.3145*TEMP)/(3.14*0.234))**0.5)*hggamma*ASA*100.
	u_HgOHCl = 0.25*(((8.*8.3145*TEMP)/(3.14*0.252))**0.5)*hggamma*ASA*100.
    u_HgOHNO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.263))**0.5)*hggamma*ASA*100.
    u_HgOHHO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.250))**0.5)*hggamma*ASA*100.
    u_HgOHO = 0.25*(((8.*8.3145*TEMP)/(3.14*0.233))**0.5)*hggamma*ASA*100.
    !Cl
    u_HgCl = 0.25*(((8.*8.3145*TEMP)/(3.14*0.235))**0.5)*hggamma*ASA*100.
    u_HgCl2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.270))**0.5)*hggamma*ASA*100.
    u_HgClNO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.281))**0.5)*hggamma*ASA*100.
    u_HgClHO2 = 0.25*(((8.*8.3145*TEMP)/(3.14*0.268))**0.5)*hggamma*ASA*100.
    u_HgClO = 0.25*(((8.*8.3145*TEMP)/(3.14*0.251))**0.5)*hggamma*ASA*100.    
    
    !! vertical deposition to the surface in cm/s
    !Inorganic
    v_HO2 = 159.3/H_alt
    v_H2O2 = 1./H_alt
    v_CH3OH = 0.09/H_alt
    v_CH3OOH = 0.9/H_alt
    v_C2H5OOH = 0.9/H_alt
    v_IC3H7OOH = 0.9/H_alt
    v_NC3H7OOH = 0.9/H_alt
    v_HCHO = 0.33/H_alt
    v_GLYOX = 3./H_alt
    v_CH3CHO = 0.33/H_alt
    v_C2H5CHO = 0.33/H_alt
    v_C3H7CHO = 0.33/H_alt
    v_HNO3 = 0.8/H_alt
    
    v_Hg = 0.46/H_alt

     
    !!Simple rate constants
    ! kro2no : ro2      + no      = ro      + no2
    !        : ro2      + no      = rono2
    KRO2NO = 2.7D-12*EXP(360/TEMP)    
    ! kro2ho2: ro2      + ho2     = rooh    + o2
    KRO2HO2 = 2.91D-13*EXP(1300/TEMP)
    ! kapho2 : rcoo2    + ho2     = products
    KAPHO2 = 5.2D-13*EXP(980/TEMP)
    ! kapno  : rcoo2    + no      = products
    KAPNO = 7.5D-12*EXP(290/TEMP)
    ! kro2no3: ro2      + no3     = products
    KRO2NO3 = 2.3D-12
    ! kno3al : no3      + rcho    = rcoo2   + hno3
    KNO3AL = 1.4D-12*EXP(-1860/TEMP)
    ! kdec   : ro                 = products
    KDEC = 1.00D+06
    KROPRIM = 2.50D-14*EXP(-300/TEMP)
    KROSEC = 2.50D-14*EXP(-300/TEMP)
    KCH3O2 = 1.03D-13*EXP(365/TEMP)
    K298CH3O2 = 3.5D-13

    !! Complex rate constants
    ! kfpan kbpan: formation and decomposition of pan
    ! iupac 1997
    kc0     = 2.70d-28*m*(temp/298.0)**(-7.1)
    kci     = 1.21d-11*(temp/298.0)**(-0.9)
    krc     = kc0/kci
    fcc     = 0.30
    fc      = 10**(dlog10(fcc)/(1+(dlog10(krc))**2))
    kfpan   = (kc0*kci)*fc/(kc0+kci)

    kd0     = 4.90d-03*m*EXP(-12100.0/temp)
    kdi     = 5.40d+16*EXP(-13830.0/temp)
    krd     = kd0/kdi
    fcd     = 0.30
    fd      = 10**(dlog10(fcd)/(1+(dlog10(krd))**2))
    kbpan   = (kd0*kdi)*fd/(kd0+kdi)

    ! kmt01  : o        + no      = no2
    ! iupac 1997, 2006 gives Fc=0.85, otherwise the same
    k0     = 1.00d-31*m*(temp/300.0)**(-1.6)
    ki     = 3.00d-11*(temp/300.0)**(0.3)
    kr     = k0/ki
    fc     = 0.85
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt01   = (k0*ki)*fcc/(k0+ki)

    ! kmt02  : o        + no2     = no3
    ! iupac 2006
    k0     = 1.30d-31*m*(temp/300.0)**(-1.5)
    ki     = 2.30d-11*(temp/300.0)**(0.24)
    kr     = k0/ki
    fc     = 0.6
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt02   = (k0*ki)*fcc/(k0+ki)

    ! kmt03  : no2      + no3     = n2o5
    ! iupac 2006
    k0     = 3.60d-30*m*(temp/300.0)**(-4.1)
    ki     = 1.90d-12*(temp/300.0)**(0.2)
    kr     = k0/ki
    fc     = 0.35
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt03   = (k0*ki)*fcc/(k0+ki)

    ! kmt04  : n2o5               = no2     + no3
    ! iupac 2006
    k0     = 1.30d-03*m*(temp/300.0)**(-3.5)*EXP(-11000.0/temp)
    ki     = 9.70d+14*(temp/300.0)**(0.1)*EXP(-11080.0/temp)
    kr     = k0/ki
    fc     = 0.35
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt04   = (k0*ki)*fcc/(k0+ki)

    ! kmt05  : oh       + co(+o2) = ho2     + co2
    ! iupac 2006
    kmt05  = 1.44d-13*(1 + m/4.2d19)

    ! kmt06  : ho2      + ho2     = h2o2    + o2
    ! water enhancement factor
    ! iupac 2001
    kmt06  = 1 + (1.40d-21*EXP(2200.0/temp)*h2o)

    ! kmt07  : oh       + no      = hono
    ! iupac 2006
    k0     = 7.40d-31*m*(temp/300.0)**(-2.4)
    ki     = 3.30d-11*(temp/300.0)**(-0.3)
    kr     = k0/ki
    fc     = EXP(-temp/1420)
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt07   = (k0*ki)*fcc/(k0+ki)

    ! kmt08  : oh       + no2     = hno3
    ! iupac 2006
    k0     = 3.30d-30*m*(temp/300.0)**(-3.0)
    ki     = 4.10d-11
    kr     = k0/ki
    fc     = 0.4
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt08   = (k0*ki)*fcc/(k0+ki)

    ! kmt09  : ho2      + no2     = ho2no2
    ! iupac 2001
    k0     = 1.80d-31*m*(temp/300.0)**(-3.2)
    ki     = 4.70d-12
    kr     = k0/ki
    fc     = 0.6
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt09   = (k0*ki)*fcc/(k0+ki)

    ! kmt10  : ho2no2             = ho2     + no2
    ! iupac 2001
    k0     = 4.10d-05*M*EXP(-10650.0/temp)
    ki     = 4.80d+15*EXP(-11170.0/temp)
    kr     = k0/ki
    fc     = 0.6
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt10   = (k0*ki)*fcc/(k0+ki)

    ! kmt11  : oh       + hno3    = h2o     + no3
    ! iupac 2006
    k1     = 2.40d-14*EXP(460.0/temp)
    k3     = 6.50d-34*EXP(1335.0/temp)
    k4     = 2.70d-17*EXP(2199.0/temp)
    k2     = (k3*M)/(1+(k3*M/k4))
    kmt11  = k1 + k2

    ! kmt12  : oh       + so2    = h2so4
    ! kmt12 iupac 2006
    k0 = 4.50d-31*M*((temp/300.0)**(-3.9))
    ki = 1.30d-12*((temp/300.0)**(-0.7))
    kr = k0/ki
    fc = 0.525
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt12   = (k0*ki)*fcc/(k0+ki)

    ! kmt13  : ch3o2    + no2     = ch3o2no2
    ! iupac 2006
    k0     = 2.50d-30*M*((temp/300.0)**(-5.5))
    ki     = 1.80d-11
    kr     = k0/ki
    fc     = 0.36
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt13   = (k0*ki)*fcc/(k0+ki)

    ! kmt14  : ch3o2no2           = ch3o2   + no2
    ! iupac 2006
    k0     = 9.00d-05*EXP(-9690.0/temp)*m
    ki     = 1.10d+16*EXP(-10560.0/temp)
    kr     = k0/ki
    fc     = 0.6
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt14   = (k0*ki)*fcc/(k0+ki)

    ! kmt15 iupac 2006
    k0     = 8.60d-29*((temp/300.0)**(-3.1))*m
    ki     = 9.00d-12*((temp/300.0)**(-0.85))
    kr     = k0/ki
    fc     =0.48
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt15   = (k0*ki)*fcc/(k0+ki)

    ! kmt16  :  oh  +  c3h6
    ! iupac 2006
    k0     = 8.00d-27*((temp/300.0)**(-3.5))*m
    ki     = 3.00d-11*((temp/300.0)**(-1.0))
    kr     = k0/ki
    fc     = 0.5
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt16   = (k0*ki)*fcc/(k0+ki)

    ! kmt17 iupac 2006
    k0    = 5.00d-30*((temp/300.0)**(-1.5))*m
    ki    = 1.00d-12
    kr    = k0/ki
    fc    = 0.17*EXP(-51/TEMP)+EXP(-TEMP/204)
    nc     = 0.75-1.27*(dlog10(fc))
    fcc    = 10**(dlog10(fc)/(1+(dlog10(kr)/nc)**2))
    kmt17   = (k0*ki)*fcc/(k0+ki)
    
    !! SOx22_HO_CH3SCH3
    KMT18 = 9.5D-39*O2*EXP(5270/TEMP)/(1+7.5D-29*O2*EXP(5610/TEMP))

    !! Iodine complex reactions 
    ! kin0      I + NO = INO
    RK0 = M*1.8E-32*((TEMP/300)**(-1))
    RKI = 1.7E-11*((TEMP/300)**0)
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    kino = (RK0/(1+RK0/RKI))*(Fcr**ETI)
    
    ! kino2      I + NO2 = INO2
    RK0 = M*3.0E-31*((TEMP/300)**(-1))
    RKI = 6.6E-11*((TEMP/300)**0)
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    kino2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)

    ! kiono2      IO + NO2 = IONO2
    RK0 = M*6.5E-31*((TEMP/300)**(-3.5))
    RKI = 7.6E-12*((TEMP/300)**(-1.5))
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    kiono2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)
    
    ! koiooh    OIO + OH = HOI + O2
    RK0 = M*1.5E-27*((TEMP/300)**(-3.93))
    RKI = 5.5E-10*exp(46/temp)*((TEMP/300)**0)
    Fcr = 0.3
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    koiooh = (RK0/(1+RK0/RKI))*(Fcr**ETI)
    
    !koioio oio + io = i2o3
    koioio = (4.687E-10-1.3855E-5*exp(-Pair*0.75/1.62265)+ &
            5.51868E-10*exp(-Pair*0.75/199.328))* &
            exp(-(0.00331+0.00514*exp(-Pair*0.75/325.68711)+ &
            0.00444*exp(-Pair*0.75/40.81609))*Temp)
            
    !koiooio oio + oio = i2o4
    koiooio = (1.1659E-9-7.79644E-10*exp(-Pair*0.75/22.09281)+ &
            1.03779E-9*exp(-Pair*0.75/568.15381))* &
            exp(-(0.00813+0.00382*exp(-Pair*0.75/45.57591)+ &
            0.00643*exp(-Pair*0.75/417.95061))*Temp)
    
    !kti2o4   I2O4 = OIO + OIO
    kti2o4 = (-1.92626E14+4.67414E13*(Pair*0.75)-3.68651E8* &
            (Pair*0.75)**2-3.09109E6*(Pair*0.75)**3)* & 
            exp((-12302.15294+252.78367*exp(-Pair*0.75/46.12733)+ &
            437.62868*exp(-Pair*0.75/428.4413))/TEMP)
    
    ! ktiono2   iono2 = io + no2
    ktiono2 = (-2.63544E13+4.32845E12*(Pair*0.75)+3.73758E8* &
            (Pair*0.75)**2-628468.76313*(Pair*0.75)**3)* &
            exp((-13847.85015+240.34465*exp(-Pair*0.75/49.27141)+ &
            451.35864*exp(-Pair*0.75/436.87605))/TEMP)
            
    !! Bromine complex reactions
    
    !kbrno2 Br + NO2 + M = BrNO2
    RK0 = M*4.42E-31*(TEMP/300)**(-2.4)
    RKI = 2.7E-11*((TEMP/300)**(0))
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    kbrno2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)

    !kbrono2   BrO + NO2 = BrONO2
    RK0 = M*5.2E-31*(TEMP/300)**(-3.2)
    RKI = 6.9E-12*((TEMP/300)**(-2.9))
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    kbrono2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)
    
    !! Mercury complex reactions
    
    !khgbrno2 Hgbr + NO2 + M = HgBrNO2
    RK0 = M*3.69E-17*(TEMP)**(-4.75)
    RKI = 1.26e-5*(TEMP)**(-2.04)
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    khgbrno2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)

    !khgbrho2   HgBr + HO2 = HgBrHO2
    RK0 = M*7.68E-19*(TEMP)**(-4.25)
    RKI = 1.24e-4*(TEMP)**(-2.53)
    Fcr = 0.6
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    khgbrho2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)    
    
	!khgclno2   HgCl + NO2 = HgClNO2
    RK0     = M*4.3E-30*(TEMP/298)**(-5.9)
    RKI     = 1.2E-10*(temp/298.0)**(-1.9)
    Fcr     = 0.60
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    khgclno2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)  

	!khgclho2   HgCl + HO2 = HgClHO2
    RK0     = M*4.3E-30*(TEMP/298)**(-5.9)
    RKI     = 6.9E-11*(temp/298.0)**(-2.4)
    Fcr     = 0.60
    ETI = (1+(dLog10(RK0/RKI))**2)**(-1)
    khgclno2 = (RK0/(1+RK0/RKI))*(Fcr**ETI)  
    
    
    RO2 = C(ind_CH3O2)
    

! End INLINED RCONST

  RCONST(1) = ((1./H_alt))
  RCONST(2) = (J(61))
  RCONST(3) = (J(62))
  RCONST(4) = (J(63))
  RCONST(5) = (J(64))
  RCONST(6) = (J(65))
  RCONST(7) = (J(66))
  RCONST(8) = (J(67))
  RCONST(9) = (J(68))
  RCONST(10) = (J(69))
  RCONST(11) = (J(70))
  RCONST(12) = (J(71))
  RCONST(13) = (J(72))
  RCONST(14) = (J(73))
  RCONST(15) = (J(74))
  RCONST(16) = (J(75))
  RCONST(17) = (J(76))
  RCONST(18) = (J(77))
  RCONST(19) = (J(78))
  RCONST(20) = (J(79))
  RCONST(21) = (J(80))
  RCONST(22) = (J(81))
  RCONST(23) = ((7.74E-14*Exp(-2939.62/TEMP)))
  RCONST(24) = ((2.1E-11*Exp(-830/TEMP)))
! RCONST(25) = constant rate coefficient
! RCONST(26) = constant rate coefficient
! RCONST(27) = constant rate coefficient
  RCONST(28) = ((7.15E-12*Exp(300/TEMP)))
  RCONST(29) = ((1.1E-12*Exp(542/TEMP)))
! RCONST(30) = constant rate coefficient
! RCONST(31) = constant rate coefficient
! RCONST(32) = constant rate coefficient
  RCONST(33) = ((1.3E-12*Exp(-1830/TEMP)))
! RCONST(34) = constant rate coefficient
! RCONST(35) = constant rate coefficient
  RCONST(36) = ((1.6E-11*Exp(440/TEMP)))
! RCONST(37) = constant rate coefficient
  RCONST(38) = ((1.5E-11*Exp(-1090/TEMP)))
  RCONST(39) = ((1.4E-11*Exp(540/TEMP)))
  RCONST(40) = (2.13E-11*Exp(180/TEMP)*(1+Exp(-Pair/191.42)))
  RCONST(41) = (3.27E-11*Exp(180/TEMP)*(1-0.65*Exp(-Pair/191.42)))
  RCONST(42) = (koioio)
  RCONST(43) = (koiooio)
! RCONST(44) = constant rate coefficient
! RCONST(45) = constant rate coefficient
  RCONST(46) = ((3.2E-13*Exp(-925/TEMP)))
  RCONST(47) = ((8.4E-11*Exp(-2620/TEMP)))
  RCONST(48) = ((4.7E-13*Exp(-1670/TEMP)))
  RCONST(49) = (9.1E-11*exp(-146/Temp))
  RCONST(50) = (2.5E14*exp(-9770/TEMP))
  RCONST(51) = (1.00E12*Exp(-9770/TEMP))
  RCONST(52) = (kti2o4)
  RCONST(53) = (ktiono2)
  RCONST(54) = ((2.4/0.005)*2.07E+15*1.*Exp(13670/TEMP))
  RCONST(55) = (kino)
  RCONST(56) = (kiono2)
  RCONST(57) = (kino2)
  RCONST(58) = (koiooh)
  RCONST(59) = (u_HOI)
  RCONST(60) = (u_HI)
  RCONST(61) = (u_INO2)
  RCONST(62) = (u_IONO2)
  RCONST(63) = (u_IO)
  RCONST(64) = (J(82))
  RCONST(65) = (J(82)*0.2)
  RCONST(66) = (J(83))
  RCONST(67) = (J(84))
  RCONST(68) = (J(85))
  RCONST(69) = (J(86))
  RCONST(70) = ((1.7E-11*Exp(-800/TEMP)))
! RCONST(71) = constant rate coefficient
  RCONST(72) = (1.5e-11*Exp(-600/TEMP))
  RCONST(73) = ((7.7E-12*Exp(-580/TEMP)))
  RCONST(74) = ((1.8E-11*Exp(-460/TEMP)))
  RCONST(75) = ((3.4E-12*Exp(545/TEMP)))
  RCONST(76) = ((8.8E-12*Exp(260/TEMP)))
  RCONST(77) = ((1.5E-14*Exp(850/TEMP)))
  RCONST(78) = ((2.4E-12*Exp(40/TEMP)))
  RCONST(79) = ((3.4E-14*Exp(860/TEMP)))
  RCONST(80) = ((2.8E-13*Exp(-12360/TEMP)))
  RCONST(81) = ((1.9E-11*Exp(240/TEMP)))
! RCONST(82) = constant rate coefficient
! RCONST(83) = constant rate coefficient
! RCONST(84) = constant rate coefficient
  RCONST(85) = (1.2E-10*Exp(-430/TEMP))
! RCONST(86) = constant rate coefficient
  RCONST(87) = (kbrno2)
  RCONST(88) = (kbrono2)
  RCONST(89) = (u_HOBr)
  RCONST(90) = (u_HBr)
  RCONST(91) = (u_BrNO2)
  RCONST(92) = (u_BrONO2)
  RCONST(93) = ((2.585E-12*Exp(280/TEMP)))
  RCONST(94) = ((1.175E-12*Exp(280/TEMP)))
  RCONST(95) = ((0.94E-12*Exp(280/TEMP)))
! RCONST(96) = constant rate coefficient
  RCONST(97) = ((0.3E-11*Exp(510/TEMP)))
  RCONST(98) = ((1.2E-11*Exp(510/TEMP)))
  RCONST(99) = (1.5E-32*EXP(TEMP/298)**(-1.86)*M)
  RCONST(100) = (1.6E-9*Exp(-7801/TEMP)*M)
! RCONST(101) = constant rate coefficient
  RCONST(102) = (2.5E-10*(TEMP/298)**(0.57))
  RCONST(103) = (2.5E-10*(TEMP/298)**(0.57))
! RCONST(104) = constant rate coefficient
  RCONST(105) = (khgbrno2)
  RCONST(106) = (khgbrho2)
! RCONST(107) = constant rate coefficient
! RCONST(108) = constant rate coefficient
  RCONST(109) = (6.0E-11*EXP(-550/TEMP))
  RCONST(110) = (3.34E-33*EXP(43/TEMP)*M)
  RCONST(111) = (1.22E-9*EXP(-5720/TEMP)*M)
! RCONST(112) = constant rate coefficient
! RCONST(113) = constant rate coefficient
! RCONST(114) = constant rate coefficient
  RCONST(115) = (khgbrno2)
  RCONST(116) = (khgbrho2)
! RCONST(117) = constant rate coefficient
  RCONST(118) = (4.1E-12*EXP(-856/TEMP))
  RCONST(119) = (6.0E-11*EXP(-550/TEMP))
  RCONST(120) = (2.25E-33*EXP(680/TEMP)*M)
! RCONST(121) = constant rate coefficient
! RCONST(122) = constant rate coefficient
! RCONST(123) = constant rate coefficient
  RCONST(124) = (khgclno2)
  RCONST(125) = (khgclho2)
! RCONST(126) = constant rate coefficient
  RCONST(127) = (4.1E-12*EXP(-856/TEMP))
  RCONST(128) = (6.0E-11*EXP(-550/TEMP))
  RCONST(129) = (J(90))
  RCONST(130) = (J(98))
  RCONST(131) = (J(95))
  RCONST(132) = (J(97))
  RCONST(133) = (J(95))
  RCONST(134) = (J(100))
  RCONST(135) = (J(96))
  RCONST(136) = (J(99))
  RCONST(137) = (J(91))
  RCONST(138) = (J(97))
  RCONST(139) = (J(107))
  RCONST(140) = (J(100))
  RCONST(141) = (J(96))
  RCONST(142) = (J(93))
  RCONST(143) = (J(108))
  RCONST(144) = (J(94))
  RCONST(145) = (J(100))
  RCONST(146) = (J(96))
  RCONST(147) = (u_HgBr)
  RCONST(148) = (u_HgBr2)
  RCONST(149) = (u_HgBrOH)
  RCONST(150) = (u_HgBrCl)
  RCONST(151) = (u_HgBrNO2)
  RCONST(152) = (u_HgBrHO2)
  RCONST(153) = (u_HgBrO)
  RCONST(154) = (u_HgOH)
  RCONST(155) = (u_HgOHOH)
  RCONST(156) = (u_HgOHCl)
  RCONST(157) = (u_HgOHNO2)
  RCONST(158) = (u_HgOHHO2)
  RCONST(159) = (u_HgOHO)
  RCONST(160) = (u_HgCl)
  RCONST(161) = (u_HgCl2)
  RCONST(162) = (u_HgClNO2)
  RCONST(163) = (u_HgClHO2)
  RCONST(164) = (u_HgClO)
  RCONST(165) = (u_HgBr/(1.4E6*24.48))
  RCONST(166) = (u_HgBr2/(1.4E6*24.48))
  RCONST(167) = (u_HgBrOH/(1.4E6*24.48))
  RCONST(168) = (u_HgBrCl/(1.4E6*24.48))
  RCONST(169) = (u_HgBrNO2/(1.4E6*24.48))
  RCONST(170) = (u_HgBrHO2/(1.4E6*24.48))
  RCONST(171) = (u_HgBrO/(1.4E6*24.48))
  RCONST(172) = (u_HgOH/(1.4E6*24.48))
  RCONST(173) = (u_HgOHOH/(1.4E6*24.48))
  RCONST(174) = (u_HgOHCl/(1.4E6*24.48))
  RCONST(175) = (u_HgOHNO2/(1.4E6*24.48))
  RCONST(176) = (u_HgOHHO2/(1.4E6*24.48))
  RCONST(177) = (u_HgOHO/(1.4E6*24.48))
  RCONST(178) = (u_HgCl/(1.4E6*24.48))
  RCONST(179) = (u_HgCl2/(1.4E6*24.48))
  RCONST(180) = (u_HgClNO2/(1.4E6*24.48))
  RCONST(181) = (u_HgClHO2/(1.4E6*24.48))
  RCONST(182) = (u_HgClO/(1.4E6*24.48))
  RCONST(183) = (v_Hg)
  RCONST(184) = (v_Hg)
  RCONST(185) = (v_Hg)
  RCONST(186) = (v_Hg)
  RCONST(187) = (v_Hg)
  RCONST(188) = (v_Hg)
  RCONST(189) = (v_Hg)
  RCONST(190) = (v_Hg)
  RCONST(191) = (v_Hg)
  RCONST(192) = (v_Hg)
  RCONST(193) = (v_Hg)
  RCONST(194) = (v_Hg)
  RCONST(195) = (v_Hg)
  RCONST(196) = (v_Hg)
  RCONST(197) = (v_Hg)
  RCONST(198) = (v_Hg)
  RCONST(199) = (v_Hg)
  RCONST(200) = (v_Hg)
! RCONST(201) = constant rate coefficient
! RCONST(202) = constant rate coefficient
! RCONST(203) = constant rate coefficient
! RCONST(204) = constant rate coefficient
! RCONST(205) = constant rate coefficient
! RCONST(206) = constant rate coefficient
! RCONST(207) = constant rate coefficient
! RCONST(208) = constant rate coefficient
! RCONST(209) = constant rate coefficient
! RCONST(210) = constant rate coefficient
! RCONST(211) = constant rate coefficient
! RCONST(212) = constant rate coefficient
! RCONST(213) = constant rate coefficient
! RCONST(214) = constant rate coefficient
! RCONST(215) = constant rate coefficient
! RCONST(216) = constant rate coefficient
! RCONST(217) = constant rate coefficient
! RCONST(218) = constant rate coefficient
  RCONST(219) = (aerosol_loss)
  RCONST(220) = (aerosol_loss)
  RCONST(221) = (aerosol_loss)
  RCONST(222) = (aerosol_loss)
  RCONST(223) = (aerosol_loss)
  RCONST(224) = (aerosol_loss)
  RCONST(225) = (aerosol_loss)
  RCONST(226) = (aerosol_loss)
  RCONST(227) = (aerosol_loss)
  RCONST(228) = (aerosol_loss)
  RCONST(229) = (aerosol_loss)
  RCONST(230) = (aerosol_loss)
  RCONST(231) = (aerosol_loss)
  RCONST(232) = (aerosol_loss)
  RCONST(233) = (aerosol_loss)
  RCONST(234) = (aerosol_loss)
  RCONST(235) = (aerosol_loss)
  RCONST(236) = (aerosol_loss)
  RCONST(237) = (5.6D-34*N2*(TEMP/300)**(-2.6)*O2+6.0D-34*O2*(TEMP/300)**(-2.6)*O2)
  RCONST(238) = (8.0D-12*EXP(-2060/TEMP))
  RCONST(239) = (KMT01)
  RCONST(240) = (5.5D-12*EXP(188/TEMP))
  RCONST(241) = (KMT02)
  RCONST(242) = (3.2D-11*EXP(67/TEMP)*O2+2.0D-11*EXP(130/TEMP)*N2)
  RCONST(243) = (1.4D-12*EXP(-1310/TEMP))
  RCONST(244) = (1.4D-13*EXP(-2470/TEMP))
  RCONST(245) = (3.3D-39*EXP(530/TEMP)*O2)
  RCONST(246) = (1.8D-11*EXP(110/TEMP))
  RCONST(247) = (4.50D-14*EXP(-1260/TEMP))
  RCONST(248) = (KMT03)
  RCONST(249) = (2.14D-10*H2O)
  RCONST(250) = (1.70D-12*EXP(-940/TEMP))
  RCONST(251) = (7.7D-12*EXP(-2100/TEMP))
  RCONST(252) = (KMT05)
  RCONST(253) = (2.9D-12*EXP(-160/TEMP))
  RCONST(254) = (2.03D-16*(TEMP/300)**4.57*EXP(693/TEMP))
  RCONST(255) = (4.8D-11*EXP(250/TEMP))
  RCONST(256) = (2.20D-13*KMT06*EXP(600/TEMP)+1.90D-33*M*KMT06*EXP(980/TEMP))
  RCONST(257) = (KMT07)
  RCONST(258) = (KMT08)
  RCONST(259) = (2.0D-11)
  RCONST(260) = (3.45D-12*EXP(270/TEMP))
  RCONST(261) = (KMT09)
  RCONST(262) = (3.2D-13*EXP(690/TEMP)*1.0)
  RCONST(263) = (4.0D-12)
  RCONST(264) = (2.5D-12*EXP(260/TEMP))
  RCONST(265) = (KMT11)
  RCONST(266) = (4.0D-32*EXP(-1000/TEMP)*M)
  RCONST(267) = (KMT12)
  RCONST(268) = (1.3D-12*EXP(-330/TEMP)*O2)
  RCONST(269) = (6.00D-06)
  RCONST(270) = (4.00D-04)
  RCONST(271) = (1.20D-15*H2O)
  RCONST(272) = (J(1))
  RCONST(273) = (J(2))
  RCONST(274) = (J(3))
  RCONST(275) = (J(4))
  RCONST(276) = (J(5))
  RCONST(277) = (J(6))
  RCONST(278) = (J(7))
  RCONST(279) = (J(8))
  RCONST(280) = (KMT04)
  RCONST(281) = (KMT10)
  RCONST(282) = (u_OH)
  RCONST(283) = (u_HO2+v_HO2)
  RCONST(284) = (u_CH3O2)
  RCONST(285) = (u_HNO3+v_HNO3)
  RCONST(286) = (u_N2O5)
  RCONST(287) = (u_NO3)
  RCONST(288) = (u_NO2)
  RCONST(289) = (v_H2O2)
  RCONST(290) = (v_CH3OH)
  RCONST(291) = (v_CH3OOH)
  RCONST(292) = (v_HCHO)
  RCONST(293) = (v_CH3CHO)
  RCONST(294) = (6.6D-12*EXP(-1240/TEMP))
  RCONST(295) = (1.85D-12*EXP(-1690/TEMP))
  RCONST(296) = (3.8D-13*EXP(780/TEMP)*(1-1/(1+498*EXP(-1160/TEMP))))
  RCONST(297) = (3.8D-13*EXP(780/TEMP)*(1/(1+498*EXP(-1160/TEMP))))
  RCONST(298) = (2.3D-12*EXP(360/TEMP)*0.001)
  RCONST(299) = (2.3D-12*EXP(360/TEMP)*0.999)
  RCONST(300) = (KMT13)
  RCONST(301) = (1.2D-12)
  RCONST(302) = (2*KCH3O2*RO2*7.18*EXP(-885/TEMP))
  RCONST(303) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(304) = (2*KCH3O2*RO2*0.5*(1-7.18*EXP(-885/TEMP)))
  RCONST(305) = (J(41))
  RCONST(306) = (5.3D-12*EXP(190/TEMP)*0.6)
  RCONST(307) = (5.3D-12*EXP(190/TEMP)*0.4)
  RCONST(308) = (J(11))
  RCONST(309) = (J(12))
  RCONST(310) = (5.5D-16)
  RCONST(311) = (5.4D-12*EXP(135/TEMP))
  RCONST(312) = (J(51))
  RCONST(313) = (4.0D-13*EXP(-845/TEMP))
  RCONST(314) = (7.2D-14*EXP(-1080/TEMP)*O2)
  RCONST(315) = (KMT14)
  RCONST(316) = (2.85D-12*EXP(-345/TEMP))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE box_Global

  RCONST(2) = (J(61))
  RCONST(3) = (J(62))
  RCONST(4) = (J(63))
  RCONST(5) = (J(64))
  RCONST(6) = (J(65))
  RCONST(7) = (J(66))
  RCONST(8) = (J(67))
  RCONST(9) = (J(68))
  RCONST(10) = (J(69))
  RCONST(11) = (J(70))
  RCONST(12) = (J(71))
  RCONST(13) = (J(72))
  RCONST(14) = (J(73))
  RCONST(15) = (J(74))
  RCONST(16) = (J(75))
  RCONST(17) = (J(76))
  RCONST(18) = (J(77))
  RCONST(19) = (J(78))
  RCONST(20) = (J(79))
  RCONST(21) = (J(80))
  RCONST(22) = (J(81))
  RCONST(64) = (J(82))
  RCONST(65) = (J(82)*0.2)
  RCONST(66) = (J(83))
  RCONST(67) = (J(84))
  RCONST(68) = (J(85))
  RCONST(69) = (J(86))
  RCONST(129) = (J(90))
  RCONST(130) = (J(98))
  RCONST(131) = (J(95))
  RCONST(132) = (J(97))
  RCONST(133) = (J(95))
  RCONST(134) = (J(100))
  RCONST(135) = (J(96))
  RCONST(136) = (J(99))
  RCONST(137) = (J(91))
  RCONST(138) = (J(97))
  RCONST(139) = (J(107))
  RCONST(140) = (J(100))
  RCONST(141) = (J(96))
  RCONST(142) = (J(93))
  RCONST(143) = (J(108))
  RCONST(144) = (J(94))
  RCONST(145) = (J(100))
  RCONST(146) = (J(96))
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE box_Rates

