! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Auxiliary Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : box_Util.f90
! Time                 : Thu Oct 21 15:31:35 2021
! Working directory    : /mnt/d/OneDrive/modelling/kpp/box_mercury_updated
! Equation file        : box.kpp
! Output root filename : box
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE box_Util

  USE box_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions


    ! Create output file
    SUBROUTINE InitSaveData_Box ()
        USE Box_Parameters
        open(10, file='outputs/Box.csv')
        
    END SUBROUTINE InitSaveData_Box  

    !Save Species Names in output file
    SUBROUTINE SaveSpeciesName_Box ()
        USE Box_Global
        USE Box_Monitor
        INTEGER i
        
        WRITE(10,9998) 'TIME', &
                        (TRIM(SPC_NAMES(LOOKAT(i))),i=1,NLOOKAT), &
                        'HgII(pg/m3)', 'Hg_dep(kg/m-2/s-1)', 'BrY'	
        9998 FORMAT(1X,A,102(1x,A))
    END SUBROUTINE SaveSpeciesName_Box
    !Save output in output file
    SUBROUTINE SaveData_Box
        USE Box_Global
        USE Box_Monitor
        INTEGER i
        REAL(dp) :: HgII,Hg_dep,BrY
        
        HgII = C(ind_HgBr) + C(ind_HgBr2) + C(ind_HgBrOH) + C(ind_HgBrCl) &
        + C(ind_HgBrNO2) + C(ind_HgBrHO2) + C(ind_HgBrO) + C(ind_HgOH) &
        + C(ind_HgOHOH)+ C(ind_HgOHCl)+ C(ind_HgOHHO2) + C(ind_HgOHNO2) &
        + C(ind_HgOHO) + C(ind_HgCl) + C(ind_HgCl2) + C(ind_HgClNO2) &
        + C(ind_HgClHO2) + C(ind_HgClO)    
         
        Hg_dep = C(ind_Hg_DryDep) + C(ind_Hg_WetDep) + C(ind_Hg_AerDep)
        
        BrY = C(ind_Br) + C(ind_Br2) + C(ind_BrO) + C(ind_HBr) + C(ind_HOBr) &
        + C(ind_BrNO2) + C(ind_BrONO2) +C(ind_BrNO) +C(ind_BrCl) + C(ind_IBr) 
               
        WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                    (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT), &
                    (HgII*200.*1000./(CFACTOR*22.45)), & 
                    (Hg_dep), &
                    (BrY/CFACTOR) 
        999   FORMAT(E24.16,102(1X,E24.16))
    END SUBROUTINE SaveData_Box 

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! UTIL - Utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!                            
! InitSaveData - Opens the data file for writing
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE box_Parameters

      open(10, file='box.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!                            
! SaveData - Write LOOKAT species in the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE box_Global
      USE box_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                   (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!                            
! CloseSaveData - Close the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE box_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!                            
! GenerateMatlab - Generates MATLAB file to load the data file 
!   Parameters : 
!                It will have a character string to prefix each 
!                species name with.                                                 
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE box_Parameters
      USE box_Global
      USE box_Monitor

      
      CHARACTER(LEN=8) PREFIX 
      INTEGER i

      open(20, file='box.m')
      write(20,*) 'load box.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = box;')
      write(20,*) 'clear box;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do
      
      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(104) = V_USER(2)
  V(89) = V_USER(3)
  V(107) = V_USER(4)
  V(82) = V_USER(5)
  V(92) = V_USER(6)
  V(61) = V_USER(7)
  V(83) = V_USER(8)
  V(67) = V_USER(9)
  V(53) = V_USER(10)
  V(1) = V_USER(24)
  V(99) = V_USER(26)
  V(98) = V_USER(27)
  V(103) = V_USER(28)
  V(90) = V_USER(29)
  V(65) = V_USER(30)
  V(66) = V_USER(31)
  V(49) = V_USER(32)
  V(2) = V_USER(33)
  V(84) = V_USER(34)
  V(87) = V_USER(35)
  V(72) = V_USER(36)
  V(68) = V_USER(37)
  V(85) = V_USER(38)
  V(3) = V_USER(39)
  V(4) = V_USER(40)
  V(5) = V_USER(41)
  V(6) = V_USER(42)
  V(7) = V_USER(43)
  V(8) = V_USER(44)
  V(9) = V_USER(45)
  V(10) = V_USER(46)
  V(55) = V_USER(47)
  V(93) = V_USER(50)
  V(56) = V_USER(52)
  V(12) = V_USER(53)
  V(13) = V_USER(55)
  V(96) = V_USER(67)
  V(64) = V_USER(68)
  V(88) = V_USER(69)
  V(80) = V_USER(70)
  V(52) = V_USER(71)
  V(77) = V_USER(72)
  V(69) = V_USER(73)
  V(25) = V_USER(74)
  V(26) = V_USER(75)
  V(27) = V_USER(76)
  V(28) = V_USER(77)
  V(29) = V_USER(78)
  V(30) = V_USER(79)
  V(31) = V_USER(80)
  V(46) = V_USER(81)
  V(94) = V_USER(82)
  V(58) = V_USER(83)
  V(86) = V_USER(84)
  V(36) = V_USER(85)
  V(54) = V_USER(86)
  V(50) = V_USER(87)
  V(32) = V_USER(88)
  V(33) = V_USER(89)
  V(34) = V_USER(90)
  V(35) = V_USER(91)
  V(37) = V_USER(92)
  V(38) = V_USER(93)
  V(95) = V_USER(94)
  V(57) = V_USER(95)
  V(51) = V_USER(96)
  V(76) = V_USER(97)
  V(70) = V_USER(98)
  V(39) = V_USER(99)
  V(40) = V_USER(100)
  V(41) = V_USER(101)
  V(42) = V_USER(102)
  V(43) = V_USER(103)
  V(14) = V_USER(104)
  V(15) = V_USER(105)
  V(16) = V_USER(106)
  V(17) = V_USER(107)
      
END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(2) = V(104)
  V_USER(3) = V(89)
  V_USER(4) = V(107)
  V_USER(5) = V(82)
  V_USER(6) = V(92)
  V_USER(7) = V(61)
  V_USER(8) = V(83)
  V_USER(9) = V(67)
  V_USER(10) = V(53)
  V_USER(24) = V(1)
  V_USER(26) = V(99)
  V_USER(27) = V(98)
  V_USER(28) = V(103)
  V_USER(29) = V(90)
  V_USER(30) = V(65)
  V_USER(31) = V(66)
  V_USER(32) = V(49)
  V_USER(33) = V(2)
  V_USER(34) = V(84)
  V_USER(35) = V(87)
  V_USER(36) = V(72)
  V_USER(37) = V(68)
  V_USER(38) = V(85)
  V_USER(39) = V(3)
  V_USER(40) = V(4)
  V_USER(41) = V(5)
  V_USER(42) = V(6)
  V_USER(43) = V(7)
  V_USER(44) = V(8)
  V_USER(45) = V(9)
  V_USER(46) = V(10)
  V_USER(47) = V(55)
  V_USER(50) = V(93)
  V_USER(52) = V(56)
  V_USER(53) = V(12)
  V_USER(55) = V(13)
  V_USER(67) = V(96)
  V_USER(68) = V(64)
  V_USER(69) = V(88)
  V_USER(70) = V(80)
  V_USER(71) = V(52)
  V_USER(72) = V(77)
  V_USER(73) = V(69)
  V_USER(74) = V(25)
  V_USER(75) = V(26)
  V_USER(76) = V(27)
  V_USER(77) = V(28)
  V_USER(78) = V(29)
  V_USER(79) = V(30)
  V_USER(80) = V(31)
  V_USER(81) = V(46)
  V_USER(82) = V(94)
  V_USER(83) = V(58)
  V_USER(84) = V(86)
  V_USER(85) = V(36)
  V_USER(86) = V(54)
  V_USER(87) = V(50)
  V_USER(88) = V(32)
  V_USER(89) = V(33)
  V_USER(90) = V(34)
  V_USER(91) = V(35)
  V_USER(92) = V(37)
  V_USER(93) = V(38)
  V_USER(94) = V(95)
  V_USER(95) = V(57)
  V_USER(96) = V(51)
  V_USER(97) = V(76)
  V_USER(98) = V(70)
  V_USER(99) = V(39)
  V_USER(100) = V(40)
  V_USER(101) = V(41)
  V_USER(102) = V(42)
  V_USER(103) = V(43)
  V_USER(104) = V(14)
  V_USER(105) = V(15)
  V_USER(106) = V(16)
  V_USER(107) = V(17)
      
END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)

      
END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE box_Util

